apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: model-engine
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: "prometheus"
        static_configs:
          - targets: ["localhost:9090"]

      - job_name: "llm-exporter"
        scrape_interval: 10s
        static_configs:
          - targets: ["metrics-exporter.model-engine.svc:9091"]
