---
apiVersion: v1
kind: Service
metadata:
  name: model-lite-observability
  namespace: model-engine
  labels:
    app: model-lite-observability
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: model-lite-observability
